# Enable Flutter's recommended lint rules
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style and formatting
    prefer_single_quotes: true
    sort_pub_dependencies: true
    always_use_package_imports: true

    # Type safety
    always_specify_types: true
    avoid_dynamic_calls: true

    # Code readability
    use_super_parameters: true
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_unnecessary_containers: true

    # Maintainability
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_positional_boolean_parameters: true
    prefer_expression_function_bodies: true
    unnecessary_late: true

    # Flutter-specific
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
