name: todo_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.7.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/models/

  fonts:
    - family: lexend
      fonts:
        - asset: assets/fonts/lexend/Lexend-Regular.ttf
        - asset: assets/fonts/lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/lexend/Lexend-Bold.ttf
          weight: 700
